[workspace]
name = "depth-anything-3"
version = "0.0.0"
description = "Depth Anything 3"
authors = ["Your Name <you@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["build_env.sh"]

[tasks]
da3 = "PYTHONPATH=src PYTORCH_ALLOC_CONF=expandable_segments:True python -m depth_anything_3.cli"

[system-requirements]
cuda = "12.4"

[dependencies]
pytorch = { version = ">=2.0", build = "*cuda*" }
torchvision = { version = "*", build = "*cuda*" }

einops = "*"
huggingface_hub = "*"
imageio = "*"
numpy = "<2"
opencv = "*"
trimesh = "*"
pre-commit = "*"
open3d = "*"
fastapi = "*"
uvicorn = "*"
requests = "*"
typer = ">=0.9.0"
pillow = "*"
omegaconf = "*"
e3nn = "*"
moviepy = "1.0.3"
plyfile = "*"
safetensors = "*"
pycolmap = "*"
xformers = "*"
cuda-nvcc = "*"
cxx-compiler = "*"
ninja = "*" 
addict = "*" 

[pypi-dependencies]

pillow-heif = "*"
evo = "*"


